### PR TITLE
py3.8 compat

### PR DESCRIPTION
**Pull request by eric-downes**
# Python 3.8+ Compatibility Fixes for compmake

1. Deprecated `imp` Module

The `imp` module was deprecated in Python 3.4 and removed in Python 3.8+, causing errors like:
`ImportError: No module named 'imp'`
Fixed by:
- Replaced direct `imp` import with conditional import based on Python version
- For Python 3: `from importlib import reload`
- For Python 2: `import imp; reload = imp.reload`
- File modified: `src/compmake/plugins/reload_module.py`

2. Deprecated `inspect.getargspec()`

The `inspect.getargspec()` function was deprecated in Python 3 in favor of `inspect.getfullargspec()`, causing errors in Python 3.8+:`AttributeError: module 'inspect' has no attribute 'getargspec'`
Fixed by:
- Updated code to conditionally use the appropriate function based on Python version
- For Python 3: `inspect.getfullargspec()`
- For Python 2: `inspect.getargspec()`
- Files modified:
  - `src/compmake/events/registrar.py` (in `register_handler()` and `broadcast_event()` functions)

3. Invalid Escape Sequences in Regular Expressions

Fixed SyntaxWarnings related to invalid escape sequences in regular expressions:
`SyntaxWarning: invalid escape sequence '\A'`
- Converting string patterns to raw strings to avoid escape sequence issues
- `'\A'` → `r'\A'`
- `'\Z'` → `r'\Z'`
- `'\x1b\[..?m'` → `r'\x1b\[..?m'`
- Files modified:
  - `src/compmake/utils/wildcards.py`
  - `src/compmake/utils/strings_with_escapes.py`

These changes have been tested by:
1. Installing the patched compmake version
2. Verifying it works with Python 3.8+ without import errors
3. Testing functionality that depends on the patched features

### Backward Compatibility

All changes maintain backward compatibility with Python 2 through the use of conditional imports and execution paths based on the Python version.

Installation
```bash
# Clone the repository
git clone https://github.com/YOUR_USERNAME/compmake.git

# Install the patched version
pip install -e ./compmake
```

### CODE REVIEW

**Comment by eric-downes** [comment]
1. Fixing the deprecated `imp` module usage in `plugins/reload_module.py` by:
   - Adding conditional imports for Python 2 vs. Python 3
   - Using `importlib.reload` for Python 3 instead of `imp.reload`

2. Fixing `inspect.getargspec()` usage in `events/registrar.py` by:
   - Using conditional code to call the appropriate function based on Python version
   - For Python 3: `inspect.getfullargspec()`
   - For Python 2: `inspect.getargspec()`

3. Fixing invalid escape sequences in regular expressions:
   - Updating string patterns in `utils/wildcards.py` to use raw strings (`r'\A'` instead of `'\A'`)
   - Updating string patterns in `utils/strings_with_escapes.py` to use raw strings
